name: Deploy Aguas Andinas Scrapping to Cloud Run

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/TU_PROYECTO_ID/cloud-run-source-deploy/fastapi-app .
          docker push us-central1-docker.pkg.dev/TU_PROYECTO_ID/cloud-run-source-deploy/fastapi-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --image=us-central1-docker.pkg.dev/TU_PROYECTO_ID/cloud-run-source-deploy/fastapi-app \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
